# A TOML plugin for GitHub CLI:
# https://moonrepo.dev/docs/proto/plugins#toml-plugin

name = "GitHub CLI"
type = "cli"

[platform.linux]
exe-path = "gh_{version}_linux_{arch}/bin/gh"
download-file = "gh_{version}_linux_{arch}.tar.gz"
checksum-file = "gh_{version}_checksums.txt"

[platform.macos]
exe-path = "gh_{version}_macOS_{arch}/bin/gh"
download-file = "gh_{version}_macOS_{arch}.zip"
checksum-file = "gh_{version}_checksums.txt"

[platform.windows]
exe-path = "bin/gh.exe"
download-file = "gh_{version}_windows_{arch}.zip"
checksum-file = "gh_{version}_checksums.txt"

[install]
download-url = "https://github.com/cli/cli/releases/download/v{version}/{download_file}"

[install.arch]
aarch64 = "arm64"
x86_64 = "amd64"
x86 = "386"

[resolve]
git-url = "https://github.com/cli/cli"
